// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegisterTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp(int type) {
    if (type == 0)
    {
        driver = new ChromeDriver(@"C:\Users\vdcuo\OneDrive\Desktop\Nam 4\Kiem thu phan mem\BTCN10\1712314-Selenium\1712314-Source\Mantis\Mantis\bin\Debug\", new ChromeOptions(), TimeSpan.FromMinutes(5));
    }
    else
    {
        driver = new FirefoxDriver(@"C:\Users\vdcuo\OneDrive\Desktop\Nam 4\Kiem thu phan mem\BTCN10\1712314-Selenium\1712314-Source\Mantis\Mantis\bin\Debug\", new FirefoxOptions(), TimeSpan.FromMinutes(50));
    }
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
    driver.Navigate().GoToUrl("http://127.0.0.1/mantis/login_page.php");
    }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void register(string username, string email) {
    driver.FindElement(By.CssSelector(".back-to-login-link.pull-left")).Click();
    driver.FindElement(By.Id("username")).SendKeys(username);
    driver.FindElement(By.Id("email-field")).SendKeys(email);
    driver.FindElement(By.CssSelector(".width-40")).Click();
    driver.Manage().Timeouts().PageLoad = TimeSpan.FromMinutes(2);
    Thread.Sleep(TimeSpan.FromMinutes(2.2));
    driver.FindElement(By.CssSelector(".width-40")).Click();
  } 
}
